# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/chrivers/bifrost:dev@sha256:3a6c3ea13d7ced67e7b4a4d45febccc8dc5d74d960c4f55a75f450f838596e30"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bifrost [DEV VERSION]"
  org.opencontainers.image.description: "Bifrost enables you to emulate a Philips Hue Bridge to control lights, groups and scenes from Zigbee2Mqtt."
  org.opencontainers.image.source: "https://github.com/chrivers/bifrost"
  org.opencontainers.image.licenses: "GNU GPLv3"
args:
  TEMPIO_VERSION: "2021.09.0"
