# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bifrost
version: "0.9.0"
slug: bifrost
description: "Bifrost enables you to emulate a Philips Hue Bridge to control lights, groups and scenes from Zigbee2Mqtt."
url: "https://github.com/chrivers/bifrost"
arch:
  - amd64
init: false

options:
  mac: "MAC Address"
schema:
  mac: "match([0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2})"

image: "ghcr.io/chrivers/bifrost"
